### ISSUE TITLE
NNP train issues (nnp-scaling and nnp-train)

### ISSUE THREAD

**Issue by yliu1240** [materialsvirtuallab/maml#132]
Hi!
I recently find that the train() function may have some issues in NNP model:

- '$nnp-scaling' seems should be executed with 'bin number' instead of input file, as '$nnp-scaling bins'. It seems that previous version will raise an error of 'gsl: init.c:33: ERROR: histogram length n should be positive integer' on terminal:
reference: https://compphysvienna.github.io/n2p2/Tools/nnp-scaling.html
- '$nnp-train' seems should be executed alone:
reference: https://compphysvienna.github.io/n2p2/Tools/nnp-train.html

I personally changed the line 618 and line 621 in _nnp.py (also nnp.py in previous mlearn package):

- p_scaling = subprocess.Popen(['nnp-scaling', input_filename]) --> p_scaling = subprocess.Popen(['nnp-scaling', '{}'.format(bin_num)])

- p_train = subprocess.Popen(['nnp-train', input_filename], --> p_train = subprocess.Popen(['nnp-train'],

And here're some of my questions:

> a. Are my changes correct? (I made these changes according to my own understanding of the n2p2 websites);

> b. The role of bin number in scaling process seems not very clear (even in original website);

> c. Is it possible to capture the error messages and show them? The error message of 'gsl histogram' can be seen when executing python on terminal, but are missing in ipynb or in program output;

> d. It seems that nnp-scaling and nnp-training support parallel computing, such as using 'mpirun -np <number>', which may decrease the training time a lot.

Thank you very much!
Best regards,

**Comment by YunxingZuo** [comment]
Thanks for the heads up! @yliu1240 

a. The change is perfectly correct. We have also made the change to the _nnp.py and set the bin number to 100 since the different bin numbers wouldn't change the file needed to run subsequent nnp-train (scaling.data). We also found that as long as we have a second argument for nnp-scaling (e.g., input_filename), the scaling.data still showed up and didn't impact the execution of nnp-train (though with an error message).

b. The bin number seems to change the histogram counts in each separate symmetry function file. Sadly, I couldn't find the exact usage of these separate files in the tutorial as well.

c. The error output mechanism has been fixed. Please take a trial.

d. We are aware that the nnp-scaling/nnp-training supports parallel computing. We did not incorporate the 'mpirun' in the code for a more general-purpose application because not all the platforms have open-mpi installed. However, we can easily add the 'mpirun' in the code manually.

Regards
