### ISSUE TITLE
NAN values in NNP training 

### ISSUE THREAD

**Issue by zhenming-xu** [materialsvirtuallab/maml#425]
Hello! 
Recently, I encountered a problem of some **NAN values in the first column of the weights.XXX.data** file when NNP training.

The following is my NNP training paramaters,

"nnp.train(train_structures=train_structures,
          train_energies=train_energies,
          train_forces=train_forces,
          cutoff_type=1, 
          r_etas=[0.5,2.0], 
          a_etas=[0.5,2.0],
          r_shift=[0.0],
          zetas=[1.0,4.0],
          r_cut=4.2, 
          hidden_layers=[4,4], 
          epochs=5)"

Very strangely, running the example(https://github.com/materialsvirtuallab/maml/blob/master/notebooks/pes/nnp/example.ipynb) in my cumputer is OK!

**Comment by JiQi535** [comment]
> Hello! Recently, I encountered a problem of some **NAN values in the first column of the weights.XXX.data** file when NNP training.
> 
> The following is my NNP training paramaters,
> 
> "nnp.train(train_structures=train_structures, train_energies=train_energies, train_forces=train_forces, cutoff_type=1, r_etas=[0.5,2.0], a_etas=[0.5,2.0], r_shift=[0.0], zetas=[1.0,4.0], r_cut=4.2, hidden_layers=[4,4], epochs=5)"
> 
> Very strangely, running the example(https://github.com/materialsvirtuallab/maml/blob/master/notebooks/pes/nnp/example.ipynb) in my cumputer is OK!

Hi Zhenming, thanks for reporting this issue. Since you mentioned that the notebook can be correctly executed, I suspect that the input you gave to the `nnp.train()` method could be problematic. I'm not sure how you chose the parameters like `r_shift`, but please make sure they are reasonable values. For example, your setting of `r_shift=[0.0]` is not found in the recommended settings given by n2p2 [(https://github.com/CompPhysVienna/n2p2/blob/master/examples/input.nn.recommended)](https://github.com/CompPhysVienna/n2p2/blob/master/examples/input.nn.recommended).

You may try the default recommended settings for the symmetry function and see if the error exists. If so, please report this issue to the n2p2 repo [(https://github.com/CompPhysVienna/n2p2),](https://github.com/CompPhysVienna/n2p2) as the weight.XXX.data file is generated in the n2p2 training process by the `nnp` executable. 

Please kindly let us know how you figured out the issue. Thanks.

**Comment by JiQi535** [comment]
Hi @zhenming-xu , can I ask if this issue is solved?

**Comment by zhenming-xu** [comment]
Hi,

I have submitted this issue to n2p2, https://github.com/CompPhysVienna/n2p2/issues/164 <https://github.com/CompPhysVienna/n2p2/issues/164>
Now, this is no reply. 

Regards! 

Zhenming Xu

***@***.***
