### ISSUE TITLE
GAPotential.train error : "No such file or directory: 'train.xml'"

### ISSUE THREAD

**Issue by AyeshaUlde** [materialsvirtuallab/maml#430]
Hello,

I was trying to run the [GAP example jupyter notebook in the mlearn repository](https://github.com/materialsvirtuallab/mlearn/tree/master/notebooks/GAP_example). I modified it to use the maml package:

![Screenshot (383)](https://user-images.githubusercontent.com/65012901/162602762-52cd8dac-ea98-4917-9d14-47425e7195f7.png)
![Screenshot (384)](https://user-images.githubusercontent.com/65012901/162602792-7765b9a1-0397-4394-a029-38d058121de1.png)

How can I fix this error?

**Comment by wilsonnieto** [comment]
Hi, where you able to solve this problem? I am facing this issue too

**Comment by AyeshaUlde** [comment]
@wilsonnieto No, I was not able to solve it.

**Comment by JiQi535** [comment]
@AyeshaUlde @wilsonnieto Thanks for reporting the error. It was probably due to an outdated gap command. I have updated the codes. Please update the maml code and see if the error is fixed.

**Comment by AyeshaUlde** [comment]
> @AyeshaUlde @wilsonnieto Thanks for reporting the error. It was probably due to an outdated gap command. I have updated the codes. Please update the maml code and see if the error is fixed.

I updated maml using the command "pip install --upgrade maml". It showed "Requirement already satisfied" for maml and all other packages. I then tried to run the code but I am still getting the same error. I suspect the error still persists because maml did not get updated. What is the appropriate command to update it?

**Comment by JiQi535** [comment]
@AyeshaUlde To always keep to the latest version of the maml package, I suggest use the protocol same as other open source packages on github, which is to use `git clone` to download the package, then use `pip installed -e .` in the folder of the downloaded maml  package to install it, and we can use `git pull` to update it whenever a new version is released. In your current situation case, you may use the below commands in your terminal:

> pip uninstall maml
> git clone https://github.com/materialsvirtuallab/maml
> cd maml; pip installed -e .

The released package on pypi is not always the latest, but we will also update it from time to time. I will update it to a new version after confirming that this bug is fixed. Please let us know how if it works. Thanks!

**Comment by AyeshaUlde** [comment]
> @AyeshaUlde To always keep to the latest version of the maml package, I suggest use the protocol same as other open source packages on github, which is to use `git clone` to download the package, then use `pip installed -e .` in the folder of the downloaded maml package to install it, and we can use `git pull` to update it whenever a new version is released. In your current situation case, you may use the below commands in your terminal:
> 
> > pip uninstall maml
> > git clone https://github.com/materialsvirtuallab/maml
> > cd maml; pip installed -e .
> 
> The released package on pypi is not always the latest, but we will also update it from time to time. I will update it to a new version after confirming that this bug is fixed. Please let us know how if it works. Thanks!

That worked. Thank you.
