### ISSUE TITLE
Flatten the structure of maml.

### ISSUE THREAD

**Issue by shyuep** [materialsvirtuallab/maml#6]
I think we should move towards a flatter organizational structure, similar to sklearn.

Basically, all implementations should be in separate files, but preceded by _. E.g.,

```
pes
- _snap
- _mtp
- ...
- __init__.py
```

The `__init__.py` will then import the relevant things. See how sklearn implement things - e.g., scikit-learn/ensemble, scikit-learn/ensemble. I like this implementation because imports are a lot simpler, and we still retain the good organization of separate files and full flexibility to move things around if needed.

**Comment by chc273** [comment]
Good idea. I will proceed with the changes.

**Comment by shyuep** [comment]
Note that even as you flatten, you cannot allow the usage of _imports in the notebooks. I see this when I look at the SNAP notebooks. These need to be fixed.

**Comment by chc273** [comment]
@shyuep The examples shall be changed . @YunxingZuo could you take a look at the pes examples? For example, you can use "from maml.utils import convert_doc", instead of "from maml.utils._data_conversion import convert_doc". I have imported the classes in __init__.py so that people can omit the private namespace. The same goes to all imports in pes examples with underscore imports.

**Comment by chc273** [comment]
@shyuep The imports to private namespace has been fixed by Yunxing. Closing it now.
